[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
serde.workspace = true
sqlx = { version = "0.7.4", features = ["chrono", "migrate", "runtime-tokio", "sqlite"] }
tokio.workspace = true
thiserror.workspace = true
