// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: default.sql

package dbsqlc

import (
	"context"
)

const queryOne = `-- name: QueryOne :one
SELECT 1
`

func (q *Queries) QueryOne(ctx context.Context, db DBTX) (int32, error) {
	row := db.QueryRow(ctx, queryOne)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
