CREATE TABLE IF NOT EXISTS days (
	date DATE PRIMARY KEY,

	lunch VARCHAR NOT NULL, 
	x_period VARCHAR NOT NULL,
	rotation_day VARCHAR NOT NULL,
	location VARCHAR NOT NULL, 
	notes VARCHAR NOT NULL, 
	cc_info VARCHAR NOT NULL, 
	grade_9 VARCHAR NOT NULL, 
	grade_10 VARCHAR NOT NULL, 
	grade_11 VARCHAR NOT NULL, 
	grade_12 VARCHAR NOT NULL, 
	
	created_ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS announcements (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,

	title VARCHAR(255) NOT NULL, 
	author VARCHAR(255) NOT NULL, 
	content VARCHAR NOT NULL, 
	display_start TIMESTAMPTZ NOT NULL,
	display_end TIMESTAMPTZ NOT NULL,

	created_ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
