CREATE TABLE IF NOT EXISTS users (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR (255) NOT NULL,
	password_hash VARCHAR NOT NULL,
	admin BOOLEAN NOT NULL DEFAULT FALSE,
	email VARCHAR (255) NOT NULL UNIQUE,
	email_verified BOOLEAN NOT NULL DEFAULT FALSE,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	created_ts TIMESTAMPTZ NOT NULL DEFAULT NOW(), 
	updated_ts TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
