[package]
name = "resources"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.6.1", features = ["serde"] }
grass = "0.13.3"
infer = "0.16.0"
keepcalm = "0.3.5"
serde.workspace = true
sha2 = "0.10.8"
tera = "1.20.0"
thiserror.workspace = true
tracing = "0.1.40"
