// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.days */
export type DaysDate = Date & { __brand: 'DaysDate' };

/** Represents the table public.days */
export default interface DaysTable {
  date: ColumnType<DaysDate, DaysDate, DaysDate>;

  lunch: ColumnType<string, string, string>;

  x_period: ColumnType<string, string, string>;

  rotation_day: ColumnType<string, string, string>;

  location: ColumnType<string, string, string>;

  notes: ColumnType<string, string, string>;

  ap_info: ColumnType<string, string, string>;

  cc_info: ColumnType<string, string, string>;

  grade_9: ColumnType<string, string, string>;

  grade_10: ColumnType<string, string, string>;

  grade_11: ColumnType<string, string, string>;

  grade_12: ColumnType<string, string, string>;

  created_ts: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_ts: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Days = Selectable<DaysTable>;

export type NewDays = Insertable<DaysTable>;

export type DaysUpdate = Updateable<DaysTable>;
