// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as SchemaMigrationsTable } from './SchemaMigrations';
import type { default as DaysTable } from './Days';

export default interface PublicSchema {
  schema_migrations: SchemaMigrationsTable;

  days: DaysTable;
}
