// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface UsersTable {
  id: ColumnType<UsersId, never, never>;

  name: ColumnType<string, string, string>;

  password_hash: ColumnType<string, string, string>;

  admin: ColumnType<boolean, boolean | undefined, boolean>;

  email: ColumnType<string, string, string>;

  email_verified: ColumnType<boolean, boolean | undefined, boolean>;

  enabled: ColumnType<boolean, boolean | undefined, boolean>;

  created_ts: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_ts: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Users = Selectable<UsersTable>;

export type NewUsers = Insertable<UsersTable>;

export type UsersUpdate = Updateable<UsersTable>;
