[package]
name = "scraping"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
csv = "1.3.0"
icalendar = { version = "0.16.2", features = ["parser"] }
itertools = "0.13.0"
serde.workspace = true
store = { version = "0.1.0", path = "../store" }
thiserror.workspace = true
